FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY tsconfig.json ./
COPY src ./src

RUN npm install -D typescript tsx
RUN npm run build

CMD ["node", "dist/index.js"]
